### ISSUE TITLE
certs server.key 

### ISSUE THREAD

**Issue by donejeh** [dsjin/web-qr-scanner#25]
Error: ENOENT: no such file or directory, open './certs/server.key'

how can generate the cert
![image](https://user-images.githubusercontent.com/14345639/205232776-986de85e-7eb0-4b7c-a51a-48c59cdee81a.png)

**Comment by dsjin** [comment]
Hello @donejeh

For generating the cert for this project.
After creating the folder, you have to generate the two files with the specified file names.  

- **_server.cert_** for a cert file
- **_server.key_** for a key

If you use [mkcert](https://github.com/FiloSottile/mkcert), you can run this command on the root project.
`mkcert -key-file ./.cert/server.key -cert-file ./.cert/server.crt localhost 127.0.0.1 ::1`

I hope it will solve your problem.
Thanks.

**Comment by donejeh** [comment]
Thank you very much , here is another problem

[image: image.png]

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
10% building 2/5 modules 3 active
...dules\eslint-loader\index.js??ref--13-0!C:\Users\EJEH\Downloads\web-qr\src\main.tsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports
(C:\Users\EJEH\Downloads\web-qr\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash
(C:\Users\EJEH\Downloads\web-qr\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError
(C:\Users\EJEH\Downloads\web-qr\node_modules\webpack\lib\NormalModule.js:471:10)
    at
C:\Users\EJEH\Downloads\web-qr\node_modules\webpack\lib\NormalModule.js:503:5
    at
C:\Users\EJEH\Downloads\web-qr\node_modules\webpack\lib\NormalModule.js:358:12
    at
C:\Users\EJEH\Downloads\web-qr\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders
(C:\Users\EJEH\Downloads\web-qr\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous>
(C:\Users\EJEH\Downloads\web-qr\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
{
  opensslErrorStack: [ 'error:03000086:digital envelope
routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

**Comment by donejeh** [comment]
C:\Users\EJEH\Downloads\web-qr>npm -v
8.19.2

C:\Users\EJEH\Downloads\web-qr>npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ***@***.***
npm WARN Found: ***@***.***
npm WARN node_modules/postcss
npm WARN   dev postcss@"^7" from the root project
npm WARN   45 more ***@***.***/optimize-cssnano-plugin, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer postcss@"^8.0.0" from ***@***.***
npm WARN node_modules/postcss-modules
npm WARN   postcss-modules@"^4.0.0" from @***@***.***
npm WARN   ***@***.***/compiler-sfc
npm WARN
npm WARN Conflicting peer dependency: ***@***.***
npm WARN node_modules/postcss
npm WARN   peer postcss@"^8.0.0" from ***@***.***
npm WARN   node_modules/postcss-modules
npm WARN     postcss-modules@"^4.0.0" from @***@***.***
npm WARN     ***@***.***/compiler-sfc
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ***@***.***
npm ERR! Found: ***@***.***
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"~4.1.5" from the root project
npm ERR!   peer typescript@">=2" from @***@***.***
npm ERR!   ***@***.***/cli-plugin-typescript
npm ERR!     dev @vue/cli-plugin-typescript@"~4.5.0" from the root project
npm ERR!   4 more (ts-loader, tslint, tsutils, tsutils)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">=4.3" from ***@***.***
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"^29.0.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: ***@***.***
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">=4.3" from ***@***.***
npm ERR!   node_modules/ts-jest
npm ERR!     dev ts-jest@"^29.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency
resolution.
npm ERR!
npm ERR! See C:\Users\EJEH\AppData\Local\npm-cache\eresolve-report.txt for
a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\EJEH\AppData\Local\npm-cache\_logs\2022-12-02T09_17_13_509Z-debug-0.log

C:\Users\EJEH\Downloads\web-qr>


*Software Engineer*

*Bachelor of Science (B.Sc) Computer Science*
*Ahmadu Bello University, Zaria*
*Portfolio <https://www.livecareer.com/me/ejeh>*

**Comment by dsjin** [comment]
@donejeh 

I found [this](https://stackoverflow.com/a/69699772) from Stackoverflow.
The problem seems to be the node version incompatibility.
You can find the solutions on the Stackoverflow thread.

Thanks.
